# Generated by Django 6.0 on 2025-12-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_uui',
            new_name='campaign_uuid',
        ),
    ]
