# Generated by Django 6.0 on 2025-12-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0002_rename_campaign_uui_campaign_campaign_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_ivr_menu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
