# Generated by Django 6.0 on 2025-12-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0003_campaign_campaign_ivr_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_concurrent_calls',
            field=models.IntegerField(default=1),
        ),
    ]
