# Generated by Django 6.0 on 2025-12-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0004_campaign_campaign_concurrent_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
