# Generated by Django 6.0 on 2025-12-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0005_campaignlead_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaignlead',
            constraint=models.UniqueConstraint(fields=('campaign', 'phone_number'), name='unique_lead_per_campaign'),
        ),
    ]
