# Generated by Django 6.0 on 2026-01-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0006_campaignlead_unique_lead_per_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_sip_gateway',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
