# Generated by Django 6.0 on 2026-01-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0008_campaign_campaign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='D4Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voip_platform', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FreeswitchEsl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_socket_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('event_socket_port', models.PositiveIntegerField()),
                ('event_socket_password', models.CharField(max_length=128)),
            ],
        ),
    ]
