# Generated by Django 6.0 on 2026-01-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0009_d4settings_freeswitchesl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d4settings',
            name='voip_platform',
            field=models.CharField(choices=[('fusionpbx', 'FusionPBX'), ('freepbx', 'FreePBX')], max_length=50),
        ),
    ]
