# Generated by Django 6.0 on 2026-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0010_alter_d4settings_voip_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_db_engine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_db_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_db_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_db_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_db_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='d4settings',
            name='voip_platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
