# Generated by Django 6.0 on 2026-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialer', '0011_d4settings_voip_platform_db_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_api_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_api_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_api_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='d4settings',
            name='voip_platform_api_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
